-- Seed 2026-08-24: alimentos faltantes + porciones comunes.
-- La tabla alimentos ya tiene ~341 filas bien pobladas; aqui se agregan pocos faltantes
-- ecuatorianos y, sobre todo, se puebla alimento_porciones (estaba vacia y es la tabla
-- que lee la app segun src/server/saludAlimentos.handlers.ts).
-- Idempotente: WHERE NOT EXISTS en ambos bloques.

-- 1. Alimentos faltantes (macros por 100 g, valores USDA/tablas LATAM)
INSERT INTO alimentos (nombre, fuente, kcal, proteina_g, carbos_g, grasa_g, fibra_g)
SELECT v.nombre, v.fuente, v.kcal, v.prot, v.carb, v.gras, v.fibra
FROM (VALUES
  ('Tomate de arbol',              'latam', 50,  2.0, 10.3, 0.4, 3.3),
  ('Jugo de tomate de arbol con azucar', 'latam', 45, 0.8, 10.5, 0.2, 0.8),
  ('Platano verde cocido',         'latam', 122, 1.2, 31.9, 0.2, 2.3),
  ('Platano maduro cocido',        'latam', 116, 1.0, 30.5, 0.2, 1.9),
  ('Aguado de gallina',            'latam', 60,  4.5,  7.0, 1.5, 0.6),
  ('Salchipapa',                   'latam', 210, 6.0, 22.0, 11.0, 1.8),
  ('Arepa de maiz',                'latam', 219, 5.2, 44.6, 2.1, 2.7),
  ('Batido de banano con leche',   'latam', 85,  2.8, 15.5, 1.6, 0.6)
) AS v(nombre, fuente, kcal, prot, carb, gras, fibra)
WHERE NOT EXISTS (SELECT 1 FROM alimentos a WHERE lower(a.nombre) = lower(v.nombre));

-- 2. Porciones comunes (tabla relacional alimento_porciones)
INSERT INTO alimento_porciones (alimento_id, nombre, gramos, orden)
SELECT a.id, v.pnombre, v.gramos, v.orden
FROM (VALUES
  -- Carbohidratos base
  ('Arroz blanco cocido',        '1 taza',            158, 1),
  ('Arroz blanco cocido',        '1/2 taza',           79, 2),
  ('Arroz blanco cocido',        '1 cucharon',        100, 3),
  ('Arroz integral cocido',      '1 taza',            195, 1),
  ('Arroz con menestra',         '1 plato',           350, 1),
  ('Arroz con pollo',            '1 plato',           350, 1),
  ('Avena en hojuelas cruda',    '1 taza',             90, 1),
  ('Avena en hojuelas cruda',    '1 cucharada',         9, 2),
  ('Avena cocida',               '1 taza',            240, 1),
  ('Quinua cocida',              '1 taza',            185, 1),
  ('Pasta cocida',               '1 taza',            140, 1),
  ('Pasta integral cocida',      '1 taza',            140, 1),
  ('Papa cocida',                '1 unidad mediana',  150, 1),
  ('Camote (batata) cocido',     '1 unidad mediana',  150, 1),
  ('Yuca cocida',                '1 taza',            160, 1),
  ('Choclo cocido ecuatoriano',  '1 choclo',          150, 1),
  ('Choclo cocido ecuatoriano',  '1 taza de granos',  165, 2),
  ('Mote (maiz cocido)',         '1 taza',            160, 1),
  ('Platano verde cocido',       '1 unidad',          150, 1),
  ('Platano maduro cocido',      '1 unidad',          140, 1),
  ('Maduro frito',               '1 unidad',          120, 1),
  ('Patacones (tostones de verde)', '1 unidad',        40, 1),
  ('Chifles',                    '1 punado',           30, 1),
  ('Chifles',                    '1 funda pequena',    45, 2),
  ('Arepa de maiz',              '1 unidad',           70, 1),
  -- Panes y tortillas
  ('Pan integral',               '1 rebanada',         32, 1),
  ('Pan blanco',                 '1 rebanada',         28, 1),
  ('Pan de molde',               '1 rebanada',         28, 1),
  ('Pan de yuca',                '1 unidad',           35, 1),
  ('Pan de hamburguesa',         '1 unidad',           60, 1),
  ('Bagel',                      '1 unidad',           95, 1),
  ('Tortilla de maiz',           '1 unidad',           30, 1),
  ('Tortilla de harina',         '1 unidad',           45, 1),
  ('Tortilla de verde',          '1 unidad',          120, 1),
  ('Galleta de soda',            '1 unidad',            6, 1),
  -- Proteinas
  ('Huevo entero cocido',        '1 unidad',           50, 1),
  ('Huevo entero crudo',         '1 unidad',           50, 1),
  ('Clara de huevo',             '1 clara',            33, 1),
  ('Yema de huevo',              '1 yema',             17, 1),
  ('Pollo pechuga cocida sin piel', '1 pechuga mediana', 120, 1),
  ('Pollo pechuga cocida sin piel', '1 filete',        100, 2),
  ('Pollo muslo cocido sin piel', '1 muslo',            95, 1),
  ('Atun en agua enlatado',      '1 lata escurrida',  120, 1),
  ('Atun en aceite enlatado',    '1 lata escurrida',  120, 1),
  ('Tilapia cocida',             '1 filete',          130, 1),
  ('Salmon cocido',              '1 filete',          125, 1),
  ('Camaron cocido',             '1 taza',            145, 1),
  ('Camaron cocido',             '1 unidad grande',     7, 2),
  ('Res molida 90/10 cocida',    '1 porcion',         100, 1),
  ('Res molida 80/20 cocida',    '1 porcion',         100, 1),
  ('Lomo de res cocido',         '1 filete',          150, 1),
  ('Tocino cocido',              '1 tira',              8, 1),
  ('Jamon cocido',               '1 tajada',           28, 1),
  ('Chorizo',                    '1 unidad',           60, 1),
  ('Salchicha vienesa',          '1 unidad',           38, 1),
  ('Tofu firme',                 '1 porcion',         100, 1),
  ('Whey protein powder',        '1 scoop',            30, 1),
  -- Lacteos
  ('Queso fresco',               '1 tajada',           30, 1),
  ('Queso mozzarella',           '1 tajada',           28, 1),
  ('Queso cheddar',              '1 tajada',           28, 1),
  ('Yogur griego natural',       '1 taza',            245, 1),
  ('Yogur griego natural',       '1 envase',          150, 2),
  ('Yogur natural entero',       '1 taza',            245, 1),
  ('Leche entera',               '1 taza',            244, 1),
  ('Leche entera',               '1 vaso',            200, 2),
  ('Leche descremada',           '1 taza',            245, 1),
  ('Leche semidescremada 2%',    '1 taza',            244, 1),
  ('Leche de almendras sin azucar', '1 taza',         240, 1),
  -- Legumbres
  ('Menestra de frijol',         '1 cucharon',        120, 1),
  ('Menestra de frijol',         '1 taza',            240, 2),
  ('Menestra de lenteja',        '1 cucharon',        120, 1),
  ('Menestra de lenteja',        '1 taza',            240, 2),
  ('Lenteja cocida',             '1 taza',            198, 1),
  ('Frijol negro cocido',        '1 taza',            172, 1),
  ('Frijol rojo cocido',         '1 taza',            177, 1),
  ('Garbanzo cocido',            '1 taza',            164, 1),
  -- Frutas
  ('Aguacate',                   '1 unidad mediana',  200, 1),
  ('Aguacate',                   '1/2 unidad',        100, 2),
  ('Banano',                     '1 unidad mediana',  118, 1),
  ('Manzana',                    '1 unidad mediana',  182, 1),
  ('Naranja',                    '1 unidad',          131, 1),
  ('Mandarina',                  '1 unidad',           88, 1),
  ('Pera',                       '1 unidad',          178, 1),
  ('Piña',                       '1 rodaja',           84, 1),
  ('Piña',                       '1 taza',            165, 2),
  ('Papaya',                     '1 taza',            145, 1),
  ('Sandia',                     '1 taza',            152, 1),
  ('Melon',                      '1 taza',            160, 1),
  ('Mango',                      '1 taza',            165, 1),
  ('Fresa',                      '1 taza',            152, 1),
  ('Uva',                        '1 taza',            151, 1),
  ('Kiwi',                       '1 unidad',           69, 1),
  ('Maracuya',                   '1 unidad',           18, 1),
  ('Granadilla',                 '1 unidad',           55, 1),
  ('Guayaba',                    '1 unidad',           55, 1),
  ('Tomate de arbol',            '1 unidad',           85, 1),
  -- Verduras
  ('Tomate',                     '1 unidad',          123, 1),
  ('Cebolla',                    '1 unidad',          110, 1),
  ('Zanahoria cruda',            '1 unidad',           61, 1),
  ('Brocoli cocido',             '1 taza',            156, 1),
  ('Lechuga',                    '1 taza',             36, 1),
  ('Pepino',                     '1 unidad',          200, 1),
  ('Pimiento rojo',              '1 unidad',          119, 1),
  ('Pimiento verde',             '1 unidad',          119, 1),
  -- Grasas, untables y azucares
  ('Aceite de oliva',            '1 cucharada',        14, 1),
  ('Aceite de oliva',            '1 cucharadita',       5, 2),
  ('Aceite vegetal',             '1 cucharada',        14, 1),
  ('Mantequilla',                '1 cucharada',        14, 1),
  ('Mantequilla de mani',        '1 cucharada',        16, 1),
  ('Miel',                       '1 cucharada',        21, 1),
  ('Azucar blanca',              '1 cucharada',        12, 1),
  ('Azucar blanca',              '1 cucharadita',       4, 2),
  ('Mermelada',                  '1 cucharada',        20, 1),
  ('Mayonesa',                   '1 cucharada',        14, 1),
  ('Ketchup',                    '1 cucharada',        15, 1),
  ('Almendra',                   '1 punado',           28, 1),
  ('Mani (cacahuate)',           '1 punado',           28, 1),
  ('Nuez',                       '1 punado',           28, 1),
  ('Semilla de chia',            '1 cucharada',        12, 1),
  ('Semilla de linaza',          '1 cucharada',        10, 1),
  ('Granola',                    '1/2 taza',           55, 1),
  ('Chocolate negro 70%',        '1 cuadrito',         10, 1),
  ('Chocolate negro 70%',        '1 barra',            50, 2),
  -- Platos ecuatorianos
  ('Encebollado',                '1 plato',           400, 1),
  ('Ceviche de camaron',         '1 plato',           300, 1),
  ('Ceviche de pescado',         '1 plato',           300, 1),
  ('Bolon de verde',             '1 unidad',          180, 1),
  ('Bolon de queso',             '1 unidad',          180, 1),
  ('Tigrillo',                   '1 plato',           300, 1),
  ('Empanada de verde',          '1 unidad',          100, 1),
  ('Empanada de viento',         '1 unidad',           80, 1),
  ('Humitas',                    '1 unidad',          120, 1),
  ('Humita',                     '1 unidad',          120, 1),
  ('Llapingacho',                '1 unidad',           80, 1),
  ('Locro de papa',              '1 plato',           350, 1),
  ('Seco de pollo',              '1 plato',           350, 1),
  ('Seco de carne',              '1 plato',           350, 1),
  ('Fritada',                    '1 porcion',         150, 1),
  ('Hornado',                    '1 porcion',         150, 1),
  ('Guatita',                    '1 plato',           350, 1),
  ('Caldo de pollo',             '1 plato',           300, 1),
  ('Sancocho',                   '1 plato',           400, 1),
  ('Tamal ecuatoriano',          '1 unidad',          140, 1),
  ('Quimbolitos',                '1 unidad',           90, 1),
  ('Salchipapa',                 '1 porcion',         250, 1),
  ('Aguado de gallina',          '1 plato',           400, 1),
  -- Bebidas
  ('Cafe negro sin azucar',      '1 taza',            240, 1),
  ('Jugo de naranja natural',    '1 vaso',            240, 1),
  ('Jugo de tomate de arbol con azucar', '1 vaso',    250, 1),
  ('Batido de banano con leche', '1 vaso',            300, 1),
  ('Gaseosa cola',               '1 lata',            355, 1),
  ('Gaseosa cola',               '1 vaso',            200, 2),
  ('Colada de avena',            '1 vaso',            250, 1),
  ('Morocho (bebida)',           '1 vaso',            250, 1),
  ('Palomitas de maiz',          '1 taza',              8, 1)
) AS v(anombre, pnombre, gramos, orden)
JOIN alimentos a ON a.nombre = v.anombre
WHERE NOT EXISTS (
  SELECT 1 FROM alimento_porciones p
  WHERE p.alimento_id = a.id AND p.nombre = v.pnombre
);
