-- Seed 2026-08-24: ejercicios de casa/estabilidad ausentes en free-exercise-db.
-- Idempotente: ON CONFLICT (slug) DO NOTHING. source = 'pancho-os'.
-- El catalogo ya tiene 880 ejercicios (free-exercise-db); esto solo agrega staples modernos que faltan.

INSERT INTO ejercicios_catalogo
  (slug, nombre_en, nombre_es, fuerza, nivel, mecanica, equipo, patron, musculos_primarios, musculos_secundarios, categoria, instrucciones_es, source)
VALUES
  ('bird-dog', 'Bird Dog', 'Perro de caza (bird dog)', 'static', 'beginner', 'compound',
   '{bodyweight}', 'anti-rotate',
   '[{"grupo":"abs","sub":"deep-core"}]', '[{"grupo":"glutes","sub":"glutes-max"},{"grupo":"back","sub":"lower-back"}]',
   'strength',
   ARRAY['En cuatro apoyos, columna neutra.','Extiende brazo y pierna contrarios sin rotar la cadera.','Pausa 2 segundos y vuelve controlado. Alterna lados.'],
   'pancho-os'),
  ('hollow-body-hold', 'Hollow Body Hold', 'Hollow hold (cuerpo hueco)', 'static', 'intermediate', 'isolation',
   '{bodyweight}', 'spinal-flexion',
   '[{"grupo":"abs","sub":"deep-core"}]', '[{"grupo":"abs","sub":"lower-abs"},{"grupo":"abs","sub":"upper-abs"}]',
   'strength',
   ARRAY['Boca arriba, lumbar pegada al piso.','Eleva hombros y piernas, brazos extendidos atras.','Manten la posicion respirando, sin arquear la espalda.'],
   'pancho-os'),
  ('wall-sit', 'Wall Sit', 'Sentadilla isometrica en pared', 'static', 'beginner', 'compound',
   '{bodyweight}', 'squat-lunge',
   '[{"grupo":"upper-leg","sub":"quads"}]', '[{"grupo":"glutes","sub":"glutes-max"}]',
   'strength',
   ARRAY['Espalda contra la pared, baja hasta muslos paralelos.','Rodillas a 90 grados sobre los tobillos.','Sostiene el tiempo objetivo sin apoyar manos en las piernas.'],
   'pancho-os'),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', 'Sentadilla bulgara', 'push', 'intermediate', 'compound',
   '{bodyweight,dumbbells,flat-bench}', 'squat-lunge',
   '[{"grupo":"upper-leg","sub":"quads"},{"grupo":"glutes","sub":"glutes-max"}]', '[{"grupo":"upper-leg","sub":"hamstrings"}]',
   'strength',
   ARRAY['Pie trasero elevado en banco o silla.','Baja vertical hasta que el muslo delantero quede paralelo.','Empuja con el talon delantero para subir. Completa el lado y cambia.'],
   'pancho-os'),
  ('nordic-hamstring-curl', 'Nordic Hamstring Curl', 'Curl nordico de isquiotibiales', 'pull', 'expert', 'isolation',
   '{bodyweight}', 'hinge',
   '[{"grupo":"upper-leg","sub":"hamstrings"}]', '[{"grupo":"glutes","sub":"glutes-max"},{"grupo":"lower-leg","sub":"upper-calf"}]',
   'strength',
   ARRAY['De rodillas, tobillos anclados (mueble o companero).','Baja el torso recto lo mas lento posible.','Amortigua con las manos y ayudate con un empujon para volver.'],
   'pancho-os'),
  ('copenhagen-plank', 'Copenhagen Plank', 'Plancha Copenhague (aductores)', 'static', 'intermediate', 'isolation',
   '{bodyweight,flat-bench}', 'hip-abduction-adduction',
   '[{"grupo":"upper-leg","sub":"inner-thigh"}]', '[{"grupo":"abs","sub":"obliques"},{"grupo":"abs","sub":"deep-core"}]',
   'strength',
   ARRAY['De lado, pie superior apoyado en banco.','Eleva la cadera hasta alinear el cuerpo.','Sostiene sin dejar caer la cadera. Cambia de lado.'],
   'pancho-os'),
  ('bear-crawl', 'Bear Crawl', 'Desplazamiento de oso', 'push', 'beginner', 'compound',
   '{bodyweight}', 'locomotion',
   '[{"grupo":"abs","sub":"deep-core"}]', '[{"grupo":"shoulders","sub":"shoulders-front"},{"grupo":"upper-leg","sub":"quads"}]',
   'cardio',
   ARRAY['En cuatro apoyos con rodillas a 2 cm del piso.','Avanza mano y pie contrarios manteniendo la cadera baja.','Espalda plana todo el trayecto, pasos cortos.'],
   'pancho-os'),
  ('bodyweight-hip-thrust', 'Hip Thrust (Bodyweight)', 'Hip thrust con peso corporal', 'push', 'beginner', 'isolation',
   '{bodyweight,flat-bench}', 'glute-isolation',
   '[{"grupo":"glutes","sub":"glutes-max"}]', '[{"grupo":"upper-leg","sub":"hamstrings"}]',
   'strength',
   ARRAY['Espalda alta apoyada en banco o sofa, pies al ancho de cadera.','Empuja con talones y extiende la cadera hasta la horizontal.','Aprieta gluteos arriba 2 segundos y baja controlado.'],
   'pancho-os')
ON CONFLICT (slug) DO NOTHING;
